### ISSUE TITLE
Matching PaymentAddress fields to autofill attributes

### ISSUE THREAD

**Issue by jcayzac** [w3c/payment-request#932] opened 2020-10-16 00:29 UTC
Hi,

There is no clear mapping between the fields of [`PaymentAddress`](https://w3c.github.io/payment-request/#physical-addresses) and the values accepted by the [`autocomplete`](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill) attribute for shipping and billing addresses: `PaymentAddress` uses descriptive semantics while `autocomplete` leaves the semantics open to regional variations. Is there a suggested mapping between the two?

Thank you.

**Comment by ianbjacobs** [comment] 2020-10-16 15:15
@marcoscaceres, @danyao, @rsolomakhin, @romandev, @aestes comments welcome!

**Comment by rsolomakhin** [comment] 2020-10-16 17:10
From the top of my head:

| PaymentAddress  | Autocomplete |
| ------------- | ------------- |
|  `recipient` | `name`  |
|  `organization` | `organization`  |
|  `addressLine` | `street-address`  |
| `dependentLocality`  | `address-level3`  |
|  `city` | `address-level2`  |
| `region  | `address-level1`  |
| `country`  | `country`  |
| `postalCode`  | `postal-code`  |
| `sortingCode`  | `postal-code`  |
| `phone`  | `tel`  |

There's no separate field for `sortingCode` in `autocomplete`. The `postal-code` field is reused with a note:

> Postal code, post code, ZIP code, CEDEX code (if CEDEX, append "CEDEX", and the arrondissement, if relevant, to the address-level2 field)

CEDEX is one type of sorting code. It may be the only type. I'm not 100% certain.

**Comment by jcayzac** [comment] 2020-10-17 00:56
@rsolomakhin Thank you very much!

Maybe this could be mentioned in a non-normative section of the spec.

**Comment by jcayzac** [comment] 2020-10-17 01:04
I'm French, and from experience address forms in France always enforce 5 digits for the postal code fields. I'm concerned that expecting the field to be made to accept CEDEX in payment handlers might not be entirely realistic.

**Comment by jcayzac** [comment] 2020-10-17 01:12
> There's no separate field for `sortingCode` in `autocomplete`. The `postal-code` field is reused with a note:
> 
> > Postal code, post code, ZIP code, CEDEX code (if CEDEX, append "CEDEX", and the arrondissement, if relevant, to the address-level2 field)

Just a small correction: the note actually says the `address-level2` field is reused, not the `postal-code` field.

Thanks!

**Comment by mnoorenberghe** [comment] 2020-10-18 22:35
As you said, `autocomplete` in the HTML spec varies by region so the mapping also varies by region. There isn't a single global mapping e.g. `address-level1` could be a `region` or `city`, `address-level2` could also be a (sub)-`region` or `city`, etc.

**Comment by jcayzac** [comment] 2020-10-19 10:19
Yeah…

In the context of a PWA using the Payment Handler API, the address input may rely on web forms annotated with `autocomplete=address-level3` etc…

Now, I am assuming that the reasoning behind fixing semantics in `PaymentAddress` is that since it is being consumed by a merchant it should not depend on the locale of either the end-user nor that of the payment handler, which kind of makes sense. So, it's up to the payment handler to "standardize" the address and produce a locale-invariant address.

(That the Contact Picker API reuses `PaymentAddress`, OTOH, really doesn't make much sense to me to be honest. But I guess that's an issue for another working group 😉 )

**Comment by marcoscaceres** [comment] 2021-02-18 05:59
Noting duplicate of #505.

**Closed** 2021-05-07 05:25 UTC
